<table class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <tr>
        <td class="label"><label for="digidennis_ean_nummer"><?php echo $this->__('EAN Nummer') ?><span class="required">*</span></label></td>
        <td class="value"><input type="text"
                                 title="<?php echo $this->__('EAN Nummer') ?>"
                                 id="digidennis_ean_nummer"
                                 class="required-entry input-text"
                                 name="payment[ean_nummer]"
                                 value="<?php echo $this->htmlEscape($this->getInfoData('ean_nummer')) ?>" />
        </td>
    </tr>
    <tr>
        <td class="label"><label for="digidennis_afstemt"><?php echo $this->__('Afstemt') ?></label></td>
        <td class="value"><input type="checkbox"
                                 id="digidennis_afstemt"
                                 title="<?php echo $this->__('Afstemt') ?>"
                                 name="payment[afstemt]" <?php if($this->getInfoData('afstemt')): ?>checked="checked"<?php endif; ?>/>
        </td>
    </tr>
</table>